#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ek_abdeckung.py - Abgleich mit der Formelsammlung von Elektronik Kompendium
==========================================================================

Quelle: https://www.elektronik-kompendium.de/sites/formeln/  (Stand des Abgleichs: 03.10.2026, 343 Themenseiten)

``ABDECKUNG`` ordnet jede Themenseite (URL-Slug, gruppiert wie auf der Uebersichtsseite) den Funktionen in
``et_formeln`` zu, die ihre Formeln abdecken.  ``HINWEISE`` dokumentiert Seiten, deren Inhalt auf EK
fehlerhaft, themenfremd oder nicht als Rechenformel abbildbar ist - dort steht, was stattdessen implementiert ist.

``test_ek_abdeckung.py`` prueft, dass jede Seite zugeordnet ist und jede genannte Funktion existiert.
Aufruf ``python ek_abdeckung.py`` gibt den Abdeckungsbericht aus.
"""
from __future__ import annotations

from typing import Dict, Tuple

import et_formeln as ef

BASIS_URL = "https://www.elektronik-kompendium.de/sites/formeln/"

ABDECKUNG: Dict[str, Dict[str, Tuple[str, ...]]] = {
    # ------------------------------------------------------------------ Physikalische Grundlagen
    "Mechanik": {
        "energie": ("kinetische_energie", "hubarbeit", "arbeit_mechanisch", "leistung_arbeit", "energie",
                    "leistung_ui", "waermemenge"),
        "mechanische-arbeit": ("arbeit_mechanisch", "hubarbeit", "kinetische_energie", "reibungskraft",
                               "spannarbeit"),
        "elektrische-arbeit": ("arbeit_uit", "arbeit_i2rt", "energie", "leistung_ui", "leistung_u2r",
                               "leistung_i2r"),
        "mechanische-leistung": ("leistung_arbeit", "leistung_kraft", "leistung_drehmoment", "leistung_mechanisch",
                                 "hubleistung", "leistung_ui"),
        "elektrische-leistung": ("leistung_ui", "leistung_i2r", "leistung_u2r", "spannung_ohm", "energie"),
        "wirkungsgrad": ("wirkungsgrad", "wirkungsgrad_carnot"),
        "energieerhaltung": ("kinetische_energie", "hubarbeit", "arbeit_mechanisch", "spannarbeit",
                             "leistung_arbeit", "waermemenge"),
        "umwandlung-von-energie": ("kinetische_energie", "hubarbeit", "arbeit_mechanisch", "arbeit_uit",
                                   "leistung_arbeit", "waermemenge"),
        "leistungsbestimmung-mit-dem-zaehler": ("zaehler_leistung", "wirkleistung", "blindleistung",
                                                "scheinleistung", "leistungsfaktor", "energie"),
    },
    "Grundlagen der Bewegung": {
        "kraft": ("kraft", "gewichtskraft", "reibungskraft", "zentripetalkraft", "federkraft", "kraft_impuls",
                  "gravitationskraft"),
        "traegheit": ("traegheitsmoment_punkt", "traegheitsmoment_zylinder", "drehimpuls", "rotationsenergie",
                      "kraft", "drehmoment_traegheit"),
        "geschwindigkeit": ("geschwindigkeit", "geschwindigkeit_beschleunigt", "weg_beschleunigt",
                            "bahngeschwindigkeit", "kmh_zu_ms", "ms_zu_kmh", "ableitung"),
        "beschleunigung": ("beschleunigung", "geschwindigkeit_beschleunigt", "weg_beschleunigt",
                           "geschwindigkeit_weg"),
        "gleichfoermige-bewegung": ("geschwindigkeit", "kmh_zu_ms", "ms_zu_kmh", "umstellen"),
        "bewegung-mit-konstanter-geschwindigkeit": ("geschwindigkeit", "umstellen"),
        "gleichmaessig-beschleunigte-und-verzoegerte-bewegung": ("weg_beschleunigt", "geschwindigkeit_beschleunigt",
                                                                  "beschleunigung", "geschwindigkeit_weg"),
        "freier-fall-als-spezielle-form-der-beschleunigten-bewegung": ("fallgeschwindigkeit", "fallzeit",
                                                                       "geschwindigkeit_beschleunigt",
                                                                       "weg_beschleunigt"),
        "kreisfoermige-bewegung": ("zentripetalkraft", "zentripetalbeschleunigung", "bahngeschwindigkeit",
                                   "kreisfrequenz_aus_T", "umlaufgeschwindigkeit", "frequenz_aus_T"),
        "gleichmaessige-kreisbewegung": ("umlaufgeschwindigkeit", "zentripetalbeschleunigung", "kreisfrequenz_aus_T",
                                         "zentripetalkraft", "frequenz_aus_T"),
        "drehbewegung": ("kreisfrequenz", "drehmoment_kraft", "drehimpuls", "traegheitsmoment_punkt",
                         "zentripetalkraft", "rotationsenergie", "bahngeschwindigkeit"),
    },
    "Ursachen von Bewegungen": {
        "kraefte": ("kraft", "gewichtskraft", "federkraft", "reibungskraft", "zentripetalkraft", "auftriebskraft"),
        "kraft-und-gewichtskraft": ("kraft", "gewichtskraft", "reibungskraft", "federkraft"),
        "addition-und-zerlegung-von-kraeften": ("kraefte_addieren", "kraftzerlegung", "kraft_resultierende"),
        "gleichgewicht-der-kraefte": ("kraefte_addieren", "drehmoment_kraft", "reibungskraft", "schwerpunkt",
                                      "kreuzprodukt"),
        "moment-und-hebel": ("hebel_kraft", "drehmoment_kraft"),
        "drehmoment": ("drehmoment_kraft", "drehmoment_traegheit", "traegheitsmoment_punkt",
                       "traegheitsmoment_zylinder"),
        "hebelgesetz": ("hebel_kraft", "drehmoment_kraft"),
        "schiefe-ebene": ("hangabtriebskraft", "normalkraft", "reibungskraft", "beschleunigung_schiefe_ebene"),
    },
    "Geometrische Berechnungen": {
        "laengenberechnung": ("umfang_kreis", "umfang_rechteck", "abstand_2d", "abstand_3d", "bogenlaenge",
                              "diagonale_rechteck"),
        "flaechenberechnung": ("flaeche_rechteck", "flaeche_dreieck", "flaeche_parallelogramm", "flaeche_trapez",
                               "flaeche_kreis", "flaeche_ellipse", "flaeche_raute", "flaeche_n_eck"),
        "volumenberechnung": ("volumen_quader", "volumen_zylinder", "volumen_kugel", "volumen_kegel",
                              "volumen_pyramide", "volumen_prisma"),
        "rauminhalt": ("volumen_quader", "volumen_prisma", "volumen_zylinder", "volumen_kugel", "volumen_kegel",
                       "volumen_pyramide"),
        "koerperberechnung": ("volumen_quader", "volumen_kugel", "volumen_zylinder", "volumen_kegel",
                              "oberflaeche_quader", "oberflaeche_kugel", "oberflaeche_zylinder", "oberflaeche_kegel",
                              "mantel_zylinder", "mantel_kegel"),
        "massenberechnung": ("dichte", "masse", "gewichtskraft", "massenanteil"),
        "dichte": ("dichte", "masse", "dichte_mittel", "dichte_temperatur", "gasdichte"),
        "rauminhalt-und-masse": ("volumen_quader", "volumen_zylinder", "volumen_kugel", "volumen_kegel",
                                 "volumen_pyramide", "dichte", "masse"),
    },
    "Temperatur und Waerme": {
        "temperatur": ("celsius_zu_fahrenheit", "fahrenheit_zu_celsius", "celsius_zu_kelvin", "kelvin_zu_celsius",
                       "fahrenheit_zu_kelvin", "kelvin_zu_fahrenheit"),
        "waermeenergie": ("waermemenge", "latente_waerme", "waermestrom_leitung", "waermestrom_strahlung",
                          "wirkungsgrad_carnot"),
        "waermemenge": ("waermemenge", "spez_waermekapazitaet", "latente_waerme"),
        "waerme-und-waermekapazitaet": ("spez_waermekapazitaet", "waermemenge", "waermekapazitaet", "innere_energie",
                                        "waermestrom_leitung"),
        "waermeleitung": ("waermestrom_leitung", "waermewiderstand", "waermestrom_rth", "waermestrom_zylinder",
                          "waermestrom_kugel"),
        "waermetransport-und-waermeuebertragung": ("waermestrom_leitung", "waermestrom_konvektion",
                                                   "waermestrom_strahlung", "waermemenge", "waermestrom_zylinder"),
        "waermewiderstand": ("waermedurchlasswiderstand", "waermewiderstand", "widerstand_reihe", "waermestrom_rth",
                             "waermedurchgangskoeffizient"),
        "elektrowaerme-und-waermenutzungsgrad": ("leistung_ui", "energie", "arbeit_i2rt", "widerstand_ohm",
                                                 "wirkungsgrad", "heizzeit", "erwaermung_dT"),
        "kuehlflaechenberechnung": ("waermeuebergangskoeffizient", "waermestrom_leitung", "waermestrom_konvektion",
                                    "kuehlflaeche", "waermedurchgangskoeffizient", "waermestrom_durchgang",
                                    "kuehlkoerper_rth"),
    },
    # ------------------------------------------------------------------ Elektronische Grundlagen
    "Elektrotechnische Grundlagen": {
        "elektrische-spannung": ("spannung_ohm", "leistung_ui", "arbeit_uit", "kapazitaet_qu", "spannung_spule",
                                 "spannungsteiler", "knotenpotentiale"),
        "elektrischer-strom": ("strom_ohm", "leistung_ui", "energie", "leistung_i2r", "leistung_u2r", "ladung",
                               "widerstand_leiter", "kapazitaet_qu", "energie_kondensator"),
        "elektrischer-widerstand": ("widerstand_ohm", "widerstand_reihe", "widerstand_parallel", "widerstand_leiter",
                                    "widerstand_temperatur"),
        "ohmsches-gesetz": ("spannung_ohm", "widerstand_ohm", "strom_ohm", "leistung_ui", "leistung_i2r",
                            "leistung_u2r"),
        "widerstand-und-leitwert": ("widerstand_ohm", "leitwert", "widerstand_reihe", "widerstand_parallel",
                                    "widerstand_leiter", "leitwert_leiter"),
        "leiterwiderstand": ("widerstand_leiter", "widerstand_temperatur", "leitwert", "widerstand_parallel",
                             "widerstand_reihe", "rho_mm2_zu_si"),
        "widerstand-und-temperatur": ("widerstand_temperatur", "temperaturkoeffizient", "widerstand_reihe",
                                      "widerstand_parallel"),
        "stromdichte": ("stromdichte", "stromdichte_feld", "widerstand_leiter", "leistung_ui"),
        "elektrische-arbeit-und-wirkungsgrad": ("arbeit_uit", "energie", "arbeit_qu", "leistung_ui", "wirkungsgrad"),
        "kirchhoffsche-gesetze": ("knotenpotentiale", "spannung_ohm", "widerstand_reihe", "widerstand_parallel",
                                  "stromteiler", "spannungsteiler"),
        "reihenschaltung-von-spannungsquellen": ("quellen_gruppenschaltung", "strom_gruppenschaltung"),
        "parallelschaltung-von-spannungsquellen": ("quellen_gruppenschaltung", "strom_gruppenschaltung"),
        "gruppenschaltung-von-gleichen-spannungsquellen": ("quellen_gruppenschaltung", "strom_gruppenschaltung"),
    },
    "Elektromagnetismus und Magnetisches Feld": {
        "elektrische-feldstaerke": ("feldstaerke_kraft", "feldstaerke_punktladung", "feldstaerke_platten",
                                    "feldstaerke_flaechenladung"),
        "elektromagnetismus": ("coulomb_kraft", "feldstaerke_punktladung", "kraft_e_feld", "spannung_ohm",
                               "flussdichte_aus_kraft", "lorentzkraft", "induktionsspannung", "h_feld_leiter"),
        "magnetische-kraftwirkung": ("lorentzkraft", "kraft_leiter", "b_feld_leiter", "fluss_winkel"),
        "stromdurchflossene-leiter-im-magnetfeld": ("kraft_leiter", "b_feld_leiter", "h_feld_leiter"),
        "elektrische-flussdichte": ("verschiebungsdichte", "verschiebungsdichte_punktladung"),
        "magnetischer-fluss": ("fluss", "fluss_winkel", "flussdichte", "induktivitaet_fluss"),
        "magnetischer-kreis": ("fluss", "flussdichte", "h_feld_spule", "durchflutung", "magn_widerstand",
                               "magn_fluss_kreis"),
        "durchflutung": ("durchflutung", "h_feld_spule", "fluss", "induktionsspannung", "spannung_spule"),
        "magnetischer-kreis-mit-luftspalt": ("magn_fluss_luftspalt", "magn_widerstand", "durchflutung", "flussdichte",
                                             "fluss"),
        "elektromagnetische-induktion": ("induktionsspannung", "fluss_winkel", "spannung_spule",
                                         "induktivitaet_fluss", "generatorspannung_scheitel", "augenblickswert"),
    },
    "Spannungsquellen": {
        "galvanische-elemente": ("nernst", "zellspannung", "elektrolyse_masse"),
        "klemmenspannung-und-leerlaufspannung": ("klemmenspannung", "innenwiderstand", "laststrom_quelle"),
        "ersatzspannungsquelle": ("innenwiderstand_lk", "kurzschlussstrom", "klemmenspannung", "laststrom_quelle",
                                  "bruecke_innenwiderstand"),
        "ersatzstromquelle": ("kurzschlussstrom", "innenwiderstand_lk", "stromteiler"),
        "spannungsanpassung": ("klemmenspannung", "laststrom_quelle", "wirkungsgrad_quelle", "spannungsteiler"),
        "stromanpassung": ("kurzschlussstrom", "stromteiler", "leistung_max_anpassung", "trafo_u2", "trafo_i2"),
        "laden-und-entladen-von-akkumulatoren": ("ladezeit_akku", "batterie_laufzeit", "wirkungsgrad_ah",
                                                 "wirkungsgrad_wh", "ah_zu_coulomb", "arbeit_uit"),
        "fotovoltaik-und-solarmodule": ("solar_einstrahlung", "solar_wirkungsgrad", "solar_leistung_temperatur",
                                        "fuellfaktor", "solar_jahresertrag", "leistung_ui"),
    },
    "Wechselstrom und Wechselspannung": {
        "winkel-und-winkelfunktionen": ("winkelfunktionen", "sinussatz_seite", "kosinussatz", "kosinussatz_winkel",
                                        "pythagoras_hypotenuse", "bogenlaenge", "grad_zu_rad"),
        "wechselstrom": ("effektivwert_sinus", "blindwiderstand_l", "blindwiderstand_c", "z_reihe_rlc",
                         "betrag_impedanz", "scheinleistung", "wirkleistung", "blindleistung", "scheinleistung_pq"),
        "periode-und-frequenz": ("frequenz_aus_T", "periodendauer", "kreisfrequenz", "kreisfrequenz_aus_T"),
        "kreisfrequenz": ("kreisfrequenz", "kreisfrequenz_aus_T", "bahngeschwindigkeit"),
        "wellenlaenge": ("wellenlaenge", "wellenlaenge_v", "photonenenergie", "wellenlaenge_photon", "snellius"),
        "augenblickswert-sinusfoermiger-wechselspannungen-und--stroeme": ("augenblickswert", "effektivwert_sinus",
                                                                          "kreisfrequenz", "phase_aus_zeit"),
        "effektivwert": ("effektivwert_sinus", "effektivwert_dreieck", "effektivwert_puls", "effektivwert_numerisch"),
        "addition-sinusfoermiger-wechselgroessen-gleicher-frequenz": ("zeigeraddition", "augenblickswert"),
        "phasenverschiebung": ("phasenwinkel_impedanz", "phase_aus_zeit", "rc_tiefpass_phase", "phasenwinkel_parallel"),
        "berechnung-von-wirkleistung-im-wechselstromkreis": ("wirkleistung", "scheinleistung", "blindleistung",
                                                             "leistungsfaktor"),
        "berechnung-von-blindleistung-im-wechselstromkreis": ("blindleistung", "blindleistung_sp",
                                                              "blindleistung_spule", "blindleistung_kondensator"),
        "berechnung-von-scheinleistung-im-wechselstromkreis": ("scheinleistung", "scheinleistung_pq", "wirkleistung",
                                                               "blindleistung", "phasenwinkel_pq", "leistungsfaktor"),
        "kompensation-der-blindleistung-bei-wechselstromverbrauchern": ("kapazitaet_aus_blindleistung",
                                                                        "induktivitaet_aus_blindleistung",
                                                                        "kompensation_kapazitaet",
                                                                        "kompensation_blindleistung"),
    },
    "Dreiphasenwechselstrom (Drehstrom)": {
        "drehstrom": ("spannung_verkettet", "wirkleistung_drehstrom", "scheinleistung_drehstrom",
                      "blindleistung_drehstrom", "leistungsfaktor", "generatorfrequenz"),
        "phasenverschiebung-im-drehstrom": ("phasenversatz", "leistungsfaktor", "phasenwinkel_pq",
                                            "scheinleistung_pq"),
        "sternschaltung-mit-symmetrischer-last": ("spannung_strang", "scheinleistung_drehstrom",
                                                  "wirkleistung_drehstrom", "blindleistung_drehstrom", "impedanz_ui"),
        "sternschaltung-mit-unsymmetrischer-gleichartiger-last": ("drehstrom_stern_unsymmetrisch",
                                                                  "neutralleiterstrom", "spannung_strang",
                                                                  "betrag_impedanz"),
        "sternschaltung-mit-unsymmetrischer-ungleichartiger-last": ("drehstrom_stern_unsymmetrisch",
                                                                    "neutralleiterstrom"),
        "dreieckschaltung-mit-symmetrischer-last": ("leiterstrom_dreieck", "strangstrom_dreieck",
                                                    "scheinleistung_drehstrom", "wirkleistung_drehstrom",
                                                    "blindleistung_drehstrom"),
        "dreieckschaltung-mit-unsymmetrischer-und-gleichartiger-last": ("drehstrom_dreieck_unsymmetrisch",
                                                                        "leiterstrom_dreieck",
                                                                        "strangstrom_dreieck"),
        "dreieckschaltung-mit-unsymmetrischer-und-ungleichartiger-last": ("drehstrom_dreieck_unsymmetrisch",
                                                                          "phasenwinkel_impedanz"),
        "berechnung-der-wirkleistung-im-drehstromkreis": ("wirkleistung_drehstrom", "wirkleistung_drehstrom_strang",
                                                          "leistung_dreieck_aus_stern"),
        "berechnung-der-blindleistung-im-drehstromkreis": ("blindleistung_drehstrom", "blindleistung_sp"),
        "berechnung-der-scheinleistung-im-drehstromkreis": ("scheinleistung_drehstrom", "scheinleistung_pq",
                                                            "leistungsfaktor"),
        "kompensation-der-blindleistung-im-drehstromkreis": ("kompensation_drehstrom_dreieck",
                                                             "kompensation_drehstrom_stern",
                                                             "kompensation_blindleistung"),
    },
    "Elektrische Messgeraete und Messtechnik": {
        "messen-der-elektrischen-spannung": ("spannungsteiler", "spannungsteiler_kapazitiv",
                                             "spannungsteiler_induktiv", "effektivwert_sinus", "vorwiderstand_messbereich"),
        "messen-der-elektrischen-stromstaerke": ("strom_ohm", "shuntwiderstand", "leistung_ui"),
        "messung-von-widerstaenden": ("widerstand_ohm", "widerstand_spannungsrichtig", "widerstand_stromrichtig",
                                      "wheatstone_rx", "widerstand_temperatur"),
        "messung-von-kondensatoren": ("kapazitaet_qu", "kapazitaet_aus_tau", "kapazitaet_aus_xc",
                                      "kapazitaet_aus_resonanz", "rc_ladespannung", "kapazitaet_reihe"),
        "messung-von-spulen": ("induktivitaet_spule", "induktivitaet_aus_xl", "induktivitaet_aus_resonanz",
                               "energie_spule", "zeitkonstante_rl"),
        "messen-der-elektrischen-leistung": ("leistung_ui", "leistung_i2r", "leistung_u2r", "wirkleistung",
                                             "wirkungsgrad"),
        "messung-von-elektrischer-arbeit-und-leistung": ("energie", "arbeit_uit", "zaehler_leistung", "joule_zu_kwh"),
        "eigenverbrauch-bei-messgeraeten": ("leistung_u2r", "leistung_i2r", "energie", "energiekosten", "wirkungsgrad"),
        "anzeigefehler-bei-messgeraeten": ("messfehler_absolut", "messfehler_relativ", "mittlerer_absoluter_fehler",
                                           "standardabweichung", "gesamtfehler"),
        "anzeigefehler-bei-zeigermessgeraeten": ("messfehler_absolut", "messfehler_relativ", "klassenfehler",
                                                 "klassenfehler_relativ"),
        "messbereichserweiterung": ("vorwiderstand_messbereich", "shuntwiderstand", "spannungsteiler", "stromteiler"),
        "messfehler-berechnung": ("messfehler_absolut", "messfehler_relativ", "mittelwert", "standardabweichung",
                                  "standardfehler", "fehlerfortpflanzung"),
    },
    # ------------------------------------------------------------------ Bauelemente
    "Kondensator": {
        "elektrische-feldstaerke": ("feldstaerke_kraft", "feldstaerke_platten"),
        "elektrische-ladung": ("coulomb_kraft", "feldstaerke_kraft", "potential_punktladung", "kapazitaet_qu",
                               "energie_kondensator", "ladung"),
        "kapazitaet-von-plattenkondensatoren": ("kapazitaet_platten", "feldstaerke_platten", "ladung_kondensator",
                                                "energie_kondensator", "kapazitaet_parallel", "kapazitaet_reihe"),
        "ladung-und-energie-bei-kondensatoren": ("kapazitaet_qu", "ladung_kondensator", "energie_kondensator",
                                                 "energie_kondensator_q", "kapazitaet_platten"),
        "laden-und-entladen-von-kondensatoren": ("rc_ladespannung", "rc_ladestrom", "rc_entladespannung",
                                                 "rc_entladestrom", "zeitkonstante_rc", "rc_ladezeit"),
        "kondensator-an-gleichspannung": ("kapazitaet_qu", "energie_kondensator", "zeitkonstante_rc",
                                          "rc_ladespannung", "rc_entladespannung"),
        "kondensator-an-wechselspannung": ("blindwiderstand_c", "z_kondensator", "strom_ohm", "blindleistung_kondensator"),
        "parallelschaltung-von-kondensatoren": ("kapazitaet_parallel", "ladung_kondensator", "energie_kondensator"),
        "reihenschaltung-von-kondensatoren": ("kapazitaet_reihe", "kapazitaet_reihe2", "teilspannung_kondensator",
                                              "spannungsteiler_kapazitiv"),
    },
    "Spule": {
        "induktivitaet": ("induktivitaet_spule", "blindwiderstand_l", "energie_spule", "spannung_spule",
                          "h_feld_spule", "induktivitaet_fluss"),
        "induktionsgesetz": ("induktionsspannung", "fluss_winkel", "spannung_spule", "induktivitaet_spule"),
        "selbstinduktion": ("spannung_spule", "induktivitaet_spule", "energie_spule", "zeitkonstante_rl",
                            "rl_einschaltstrom", "rl_freilaufstrom"),
        "induktionsspannung": ("induktionsspannung", "fluss_winkel", "induktionsspannung_bewegt", "spannung_spule"),
        "spule-an-gleichspannung": ("induktivitaet_spule", "spannung_spule", "zeitkonstante_rl", "rl_einschaltstrom",
                                    "rl_spulenspannung", "energie_spule"),
        "spule-an-wechselspannung": ("blindwiderstand_l", "z_spule", "effektivwert_sinus", "blindleistung_spule"),
        "reihenschaltung-von-spulen": ("induktivitaet_reihe", "induktivitaet_reihe_gekoppelt", "spannungsteiler_induktiv",
                                       "blindwiderstand_l"),
        "parallelschaltung-von-spulen": ("induktivitaet_parallel", "blindwiderstand_l", "widerstand_parallel"),
    },
    "Transformator": {
        "transformator-ohne-verluste": ("trafo_u2", "trafo_i2", "trafo_z_primaer", "trafo_uebersetzung"),
        "transformator-mit-verlusten": ("trafo_wirkungsgrad", "trafo_kupferverluste", "trafo_u2", "trafo_i2"),
        "berechnung-von-netztransformatoren": ("trafo_hauptgleichung", "trafo_fluss", "trafo_wirkungsgrad",
                                               "trafo_kurzschlussimpedanz", "trafo_uk", "trafo_kurzschlussstrom"),
        "uebersetzung-von-spannung-beim-transformator": ("trafo_u2", "trafo_uebersetzung", "induktionsspannung"),
        "uebersetzung-von-strom-beim-transformator": ("trafo_i2", "trafo_uebersetzung"),
        "uebersetzung-von-widerstand-beim-transformator": ("trafo_z_primaer", "trafo_uebersetzung"),
    },
    "Nichtlineare Widerstaende": {
        "heissleiter-ntc": ("ntc_widerstand", "ntc_b_wert", "ntc_temperatur", "ntc_tk", "eigenerwaermung"),
        "kaltleiter-ptc": ("ptc_widerstand_linear", "ptc_widerstand_exp", "temperaturkoeffizient", "eigenerwaermung",
                           "leistung_i2r"),
        "spannungsabhaengiger-widerstand-vdr": ("vdr_strom", "vdr_spannung", "vdr_widerstand", "vdr_alpha"),
        "fotowiderstand-ldr": ("ldr_widerstand", "ldr_beleuchtungsstaerke", "ldr_gamma", "spannungsteiler"),
        "feldplatte": ("feldplatte_widerstand",),
    },
    "Halbleiterdioden": {
        "schaltdioden": ("diode_strom", "thermospannung", "sperrschichtkapazitaet", "spannung_ohm"),
        "gleichrichterdioden": ("leistung_ui", "thyristor_verlustleistung", "welligkeit", "wirkungsgrad"),
        "z-dioden": ("zdiode_leistung", "zdiode_rz", "zdiode_vorwiderstand", "zdiode_strom"),
        "kapazitaetsdioden": ("sperrschichtkapazitaet", "kapazitaetsverhaeltnis", "resonanzfrequenz"),
    },
    "Bipolare Transistoren": {
        "berechnung-der-spannungsverstaerkung-beim-bipolaren-transistor": ("spannungsverstaerkung", "emitterschaltung_vu",
                                                                           "emitterschaltung_rin", "bjt_re"),
        "berechnung-der-stromverstaerkung-beim-bipolaren-transistor": ("bjt_ic", "stromverstaerkung",
                                                                       "bjt_beta_aus_alpha", "bjt_alpha_aus_beta"),
        "berechnung-der-verlustleistung-beim-bipolaren-transistor": ("bjt_verlustleistung", "leistung_ui"),
    },
    "Feldeffekttransistoren": {
        "berechnung-der-spannungsverstaerkung-beim-feldeffekttransistor": ("sourceschaltung_vu", "fet_gm", "fet_rds",
                                                                           "widerstand_parallel2"),
        "berechnung-der-restspannung-beim-feldeffekttransistor": ("fet_restspannung", "fet_id_ohmsch",
                                                                  "mosfet_id_saettigung", "fet_uds_sat", "fet_k"),
        "berechnung-der-verlustleistung-beim-feldeffekttransistor": ("fet_leitverluste", "fet_schaltverluste",
                                                                     "leistung_ui"),
    },
    "Fotohalbleiter": {
        "fotowiderstand": ("ldr_widerstand", "ldr_beleuchtungsstaerke", "spannungsteiler", "leistung_u2r"),
        "fotodiode": ("diode_strom", "fotostrom", "fotostrom_quanten", "sperrschichtkapazitaet"),
        "leuchtdiode": ("led_vorwiderstand", "led_vorwiderstand_leistung", "leistung_ui"),
        "fototransistor": ("fotostrom", "bjt_ic", "bjt_uce"),
        "optokoppler": ("ctr", "bjt_uce", "led_vorwiderstand"),
    },
    "Spannungserzeuger": {
        "hallgenerator": ("hall_spannung", "hall_konstante", "hall_flussdichte", "stromdichte"),
        "fotoelement-und-solarzelle": ("fotostrom", "solar_leerlaufspannung", "fuellfaktor", "solar_wirkungsgrad",
                                       "leistung_ui"),
    },
    "Leistungselektronik": {
        "thyristor": ("thyristor_durchlassspannung", "thyristor_verlustleistung", "zuendwiderstand"),
        "zuenden-von-thyristoren": ("steuerwinkel", "gesteuert_m1", "gesteuert_b2", "zuendwiderstand"),
        "triac": ("steuerwinkel", "phasenanschnitt_effektivwert", "wirkleistung", "scheinleistung"),
        "zuenden-von-triacs": ("steuerwinkel", "phasenanschnitt_effektivwert", "effektivwert_sinus"),
        "phasenanschnittsteuerung": ("steuerwinkel", "phasenanschnitt_effektivwert", "phasenanschnitt_leistung"),
        "schwingungspaketsteuerung": ("schwingungspaket_leistung", "schwingungspaket_effektivwert"),
        "wechselstromsteller": ("phasenanschnitt_effektivwert", "phasenanschnitt_leistung", "schwingungspaket_leistung",
                                "betrag_impedanz"),
        "vielperiodensteuerung": ("schwingungspaket_leistung", "schwingungspaket_effektivwert"),
    },
    "Netzgeraete": {
        "spannungsstabilisierte-netzgeraete": ("laengsregler_ua", "brummspannung", "laengsregler_verlust",
                                               "wirkungsgrad", "netzausregelung", "lastausregelung"),
        "stromstabilisierte-netzgeraete": ("konstantstrom", "zdiode_vorwiderstand"),
        "schaltnetzgeraet": ("tastgrad", "tiefsetzsteller_ua", "hochsetzsteller_ua", "inverswandler_ua",
                             "tiefsetzsteller_l", "tiefsetzsteller_c", "hochsetzsteller_l", "hochsetzsteller_c",
                             "wirkungsgrad"),
    },
    "Operationsverstaerker": {
        "operationsverstaerker-als-invertierender-verstaerker": ("opv_invertierend", "opv_ua_invertierend"),
        "operationsverstaerker-als-nicht-invertierender-verstaerker": ("opv_nichtinvertierend",
                                                                       "opv_ua_nichtinvertierend"),
        "operationsverstaerker-als-differenzverstaerker-subtrahierer": ("opv_differenz",),
        "operationsverstaerker-als-summierverstaerker-addierer": ("opv_summierer", "opv_summierer_n"),
        "operationsverstaerker-als-integrator": ("opv_integrator", "opv_integrator_betrag", "zeitkonstante_rc"),
        "operationsverstaerker-als-tiefpass": ("opv_tiefpass_betrag", "grenzfrequenz_rc"),
        "operationsverstaerker-als-differenzierer": ("opv_differenzierer", "opv_differenzierer_betrag"),
        "operationsverstaerker-als-hochpass": ("opv_hochpass_betrag", "grenzfrequenz_rc"),
    },
    # ------------------------------------------------------------------ Schaltungstechnik
    "Schaltungen mit Widerstaenden": {
        "parallelschaltung-von-widerstaenden": ("widerstand_parallel", "widerstand_parallel2", "strom_ohm"),
        "reihenschaltung-von-widerstaenden": ("widerstand_reihe", "spannungsteiler"),
        "gemischte-schaltungen-von-widerstaenden": ("widerstand_reihe", "widerstand_parallel", "stern_zu_dreieck",
                                                    "dreieck_zu_stern"),
        "spannungsteiler-mit-widerstaenden": ("spannungsteiler", "strom_ohm"),
        "unbelasteter-spannungsteiler-mit-widerstaenden": ("spannungsteiler",),
        "belasteter-spannungsteiler-mit-widerstaenden": ("spannungsteiler_belastet", "widerstand_parallel2"),
        "brueckenschaltung-mit-widerstaenden": ("wheatstone_rx", "brueckenspannung", "bruecke_gesamtwiderstand",
                                                "bruecke_innenwiderstand"),
        "abgeglichene-brueckenschaltung-mit-widerstaenden": ("wheatstone_rx", "bruecke_gesamtwiderstand"),
        "unabgeglichene-brueckenschaltung-mit-widerstaenden": ("brueckenspannung", "bruecke_innenwiderstand",
                                                               "bruecke_strom"),
        "led-mit-vorwiderstand": ("led_vorwiderstand", "led_vorwiderstand_leistung"),
    },
    "Gleichrichterschaltungen": {
        "gleichrichtung": ("gleichrichtwert_einweg", "effektivwert_einweg", "gleichrichtwert_sinus",
                           "effektivwert_sinus", "scheitelfaktor", "formfaktor"),
        "gleichrichterschaltungen": ("gleichrichtwert_einweg", "effektivwert_einweg", "gleichrichtwert_sinus",
                                     "brummspannung", "gleichspannung_geglaettet", "trafo_u2"),
        "berechnung-der-brummspannung": ("brummspannung", "brummspannung_effektiv"),
        "glaettung-und-siebung": ("brummspannung", "siebfaktor_rc", "siebfaktor_lc", "welligkeit"),
        "siebung-mit-rc-schaltung": ("zeitkonstante_rc", "grenzfrequenz_rc", "rc_tiefpass_betrag", "siebfaktor_rc"),
        "siebung-mit-lc-schaltung": ("resonanzfrequenz", "lc_tiefpass", "siebfaktor_lc"),
    },
    "Spannungsstabilisierung": {
        "spannung-stabilisieren": ("zdiode_vorwiderstand", "laengsregler_ua", "brummspannung", "inverswandler_ua"),
        "strom-stabilisieren": ("konstantstrom", "spannungsteiler"),
        "z-diode": ("zdiode_vorwiderstand", "zdiode_leistung", "zdiode_strom"),
        "vorwiderstand-fuer-die-spannungsstabilisierung-mit-z-diode": ("zdiode_vorwiderstand",
                                                                       "zdiode_vorwiderstand_bereich",
                                                                       "led_vorwiderstand_leistung"),
        "spannungsstabilisierung-mit-z-diode": ("zdiode_vorwiderstand", "zdiode_strom", "zdiode_leistung",
                                                "strom_ohm"),
        "parallelstabilisierung-mit-z-diode": ("zdiode_vorwiderstand", "zdiode_strom", "zdiode_leistung",
                                               "zdiode_laststrom_max", "zdiode_vorwiderstand_bereich"),
        "reihenstabilisierung": ("reihenstabilisierung_ua", "laengsregler_verlust", "zdiode_vorwiderstand"),
        "spannungsstabilisierung-mit-spannungsreglern": ("laengsregler_ua", "laengsregler_verlust", "wirkungsgrad",
                                                         "sperrschichttemperatur", "kuehlkoerper_rth"),
    },
    "Bipolarer Transistor": {
        "bipolarer-transistor-als-verstaerker": ("bjt_ic", "bjt_ie", "emitterschaltung_vu", "emitterschaltung_rin",
                                                 "bjt_re"),
        "arbeitspunkteinstellung-mit-basis-vorwiderstand": ("bjt_basisvorwiderstand", "bjt_ic", "bjt_ie", "bjt_uce"),
        "arbeitspunkteinstellung-mit-basis-spannungsteiler": ("spannungsteiler", "bjt_basisvorwiderstand", "bjt_ic",
                                                              "bjt_uce", "bjt_ie_spannungsteiler"),
        "basisspannungsteiler-und-stabilisierung-des-arbeitspunktes": ("bjt_ie_spannungsteiler", "spannungsteiler",
                                                                       "bjt_uce"),
        "gleichstromgroessen-in-der-emitterschaltung": ("bjt_basisvorwiderstand", "bjt_ic", "bjt_ie", "bjt_uce"),
        "emitterschaltung-mit-stromgegenkopplung": ("emitterschaltung_vu", "bjt_re", "emitterschaltung_rin"),
        "emitterschaltung-mit-spannungsgegenkopplung": ("emitterschaltung_vu", "bjt_re", "emitterschaltung_rin",
                                                        "verstaerkung_gegenkopplung"),
        "emitterschaltung-als-wechselstromverstaerker": ("emitterschaltung_vu", "emitterschaltung_rin",
                                                         "leistungsverstaerkung_vu"),
        "koppelkondensator-beim-wechselstromverstaerker": ("koppelkondensator", "grenzfrequenz_rc",
                                                           "rc_hochpass_betrag"),
        "kollektorschaltung": ("kollektorschaltung_vu", "kollektorschaltung_rout", "emitterschaltung_rin"),
        "basisschaltung": ("basisschaltung_vu", "bjt_re", "bjt_alpha_aus_beta"),
    },
    "Elektronische Schalter": {
        "transistor-als-schalter": ("schalter_ic", "schalter_rb", "bjt_uce", "bjt_verlustleistung"),
        "transistoren-als-elektronische-schalter-bei-ohmscher-last": ("schalter_ic", "schalter_rb", "leistung_ui"),
        "transistoren-als-elektronische-schalter-bei-induktiver-last": ("spannung_spule", "energie_spule",
                                                                        "schaltzeit_induktiv"),
        "transistoren-als-elektronische-schalter-bei-kapazitiver-last": ("strom_kondensator", "rc_ladezeit",
                                                                         "energie_kondensator", "umladeleistung"),
        "elektronischer-schalter-mit-ttl-und-cmos-bausteinen": ("fan_out", "gatterlaufzeit", "umladeleistung",
                                                                "grenzfrequenz_rc"),
        "interface-schaltungen": ("spannungsteiler", "led_vorwiderstand", "schalter_rb", "ctr"),
    },
    "Feldeffekttransistor (FET)": {
        "sourceschaltung": ("sourceschaltung_vu", "fet_gm", "mosfet_id_saettigung"),
        "drainschaltung": ("drainschaltung_vu", "mosfet_id_saettigung"),
        "feldeffekttransistor-als-verstaerker": ("fet_id_ohmsch", "mosfet_id_saettigung", "fet_gm", "sourceschaltung_vu",
                                                 "fet_rds"),
    },
    "Kippschaltungen": {
        "astabile-kippstufe": ("ne555_astabil", "multivibrator_periode", "frequenz_aus_T"),
        "astabile-kippstufe-mit-transistoren": ("multivibrator_periode", "kippzeit_transistor"),
        "astabile-kippstufe-mit-operationsverstaerker": ("opv_astabil_periode",),
        "monostabile-kippstufe": ("ne555_monostabil", "rc_ladespannung", "rc_ladezeit"),
        "monostabile-kippstufe-mit-transistoren": ("kippzeit_transistor", "schalter_ic"),
        "monostabile-kippstufe-mit-operationsverstaerker": ("opv_monoflop",),
        "bistabile-kippstufe": ("schmitt_invertierend", "schmitt_nichtinvertierend", "spannungsteiler"),
        "schmitt-trigger": ("schmitt_invertierend", "schmitt_nichtinvertierend"),
        "schwellwertschalter": ("schaltschwellen", "spannungsteiler"),
        "schmitt-trigger-mit-transistoren": ("schaltschwellen", "spannungsteiler"),
        "schmitt-trigger-mit-operationsverstaerker": ("schmitt_invertierend", "schmitt_nichtinvertierend"),
    },
    "Schwingkreise": {
        "schwingkreise": ("resonanzfrequenz", "resonanzkreisfrequenz", "guete_reihe", "bandbreite",
                          "energie_schwingkreis"),
        "guete-bei-schwingkreisen": ("guete_reihe", "guete_parallel", "guete_aus_bandbreite", "bandbreite"),
        "bandbreite-bei-schwingkreisen": ("bandbreite", "bandbreite_reihe", "grenzfrequenzen_kreis",
                                          "guete_aus_bandbreite"),
        "reihenschwingkreis": ("resonanzfrequenz", "z_reihe_rlc", "guete_reihe", "spannungsueberhoehung", "bandbreite"),
        "parallelschwingkreis": ("resonanzfrequenz", "resonanzwiderstand_parallel", "guete_parallel",
                                 "z_parallel_rlc", "bandbreite"),
        "wellenausbreitung": ("wellenlaenge_v", "wellenzahl", "frequenz_aus_T", "kreisfrequenz", "augenblickswert",
                              "doppler"),
        "resonanzfrequenz": ("resonanzfrequenz", "eigenfrequenz_feder", "daempfungsgrad_mech", "guete_reihe"),
        "resonanzwiderstand": ("resonanzwiderstand_parallel", "z_reihe_rlc", "guete_reihe", "bandbreite"),
    },
    "Filterschaltungen": {
        "rc-tiefpass": ("grenzfrequenz_rc", "rc_tiefpass_betrag", "rc_tiefpass_phase", "tiefpass_1"),
        "lr-tiefpass": ("grenzfrequenz_rl", "rl_tiefpass_betrag", "tiefpass_1"),
        "cr-hochpass": ("grenzfrequenz_rc", "rc_hochpass_betrag", "rc_hochpass_phase", "hochpass_1"),
        "rl-hochpass": ("grenzfrequenz_rl", "rl_hochpass_betrag", "hochpass_1"),
        "bandpass": ("mittenfrequenz", "bandbreite_grenzen", "guete_aus_bandbreite", "bandpass_2",
                     "bandpass_1_betrag", "daempfungsgrad_aus_guete"),
        "bandsperre": ("mittenfrequenz", "bandbreite_grenzen", "guete_aus_bandbreite", "bandsperre_2", "betrag_db"),
        "spulenverluste": ("leistung_i2r", "verlustfaktor_spule", "guete_spule"),
        "kondensatorverluste": ("verlustleistung_kondensator", "verlustfaktor_kondensator_reihe", "blindwiderstand_c"),
    },
    "Signalgeneratoren": {
        "rechteckgenerator": ("tastgrad", "effektivwert_puls", "mittelwert_puls", "frequenz_aus_T"),
        "rechteckgenerator-mit-transistoren": ("kippzeit_transistor", "multivibrator_periode", "tastgrad"),
        "rechteckgenerator-mit-operationsverstaerker": ("opv_astabil_periode", "schmitt_invertierend"),
        "rechteckgenerator-mit-monostabilen-kippstufen": ("rc_ladezeit", "ne555_monostabil", "opv_monoflop"),
        "saegezahngenerator": ("rampensteilheit", "rc_ladespannung", "frequenz_aus_T"),
        "saegezahngenerator-mit-einrichtungs-thyristordiode": ("rc_ladezeit", "effektivwert_dreieck",
                                                               "brummspannung_effektiv"),
        "saegezahngenerator-mit-unijunction-transistor": ("ujt_periode", "ujt_hoeckerspannung", "rc_ladezeit"),
        "saegezahngenerator-mit-operationsverstaerker": ("saegezahn_anstieg", "saegezahn_frequenz", "opv_integrator",
                                                         "schmitt_nichtinvertierend"),
        "sinusgenerator": ("augenblickswert", "effektivwert_sinus", "kreisfrequenz", "wien_frequenz"),
        "lc-generator": ("resonanzfrequenz", "resonanzkreisfrequenz", "guete_reihe", "bandbreite"),
        "rc-generator": ("phasenschieber_frequenz", "wien_frequenz", "zeitkonstante_rc", "rc_ladespannung"),
        "phasenschiebergeneratoren": ("phasenschieber_frequenz",),
        "wien-brueckengenerator": ("wien_frequenz", "opv_nichtinvertierend", "ptc_widerstand_linear"),
        "funktionsgeneratoren": ("frequenz_aus_T", "effektivwert_sinus", "effektivwert_dreieck", "effektivwert_puls",
                                 "wien_frequenz", "resonanzfrequenz"),
    },
    "Verstaerker": {
        "verstaerkung": ("spannungsverstaerkung", "stromverstaerkung", "leistungsverstaerkung", "db_spannung",
                         "db_leistung", "verstaerkung_gegenkopplung"),
        "daempfung": ("daempfungsgrad_mech", "eigenfrequenz_feder", "log_dekrement", "daempfungsgrad_rlc",
                      "eigenkreisfrequenz_gedaempft", "db_spannung"),
        "klirren-und-klirrfaktor": ("klirrfaktor", "klirrfaktor_gesamt", "db_spannung"),
        "rauschen": ("snr_db", "rauschleistung", "rauschzahl", "friis", "rauschtemperatur",
                     "rauschspannung_thermisch"),
        "wechselspannungsverstaerker": ("spannungsverstaerkung", "impedanz_ui", "leistungsverstaerkung_vu",
                                        "verstaerkung_frequenz", "phase_verstaerker", "db_spannung"),
        "einstufiger-verstaerker": ("spannungsverstaerkung", "stromverstaerkung", "leistungsverstaerkung",
                                    "widerstand_ohm"),
        "mehrstufiger-verstaerker": ("verstaerkung_kette", "verstaerkung_frequenz", "spannungsverstaerkung"),
        "leistungsverstaerker": ("leistungsverstaerkung", "ausgangsleistung_sinus", "wirkungsgrad",
                                 "grenzfrequenz_rc"),
        "eintakt-a-endstufe": ("ausgangsleistung_sinus", "verlustleistung", "wirkungsgrad", "klirrfaktor"),
        "gegentakt-endstufe": ("ausgangsleistung_sinus", "wirkungsgrad_b_endstufe", "klirrfaktor",
                               "bjt_verlustleistung"),
        "integrierter-leistungsverstaerker": ("ausgangsleistung_sinus", "slew_rate", "opv_slew_fmax", "snr_db",
                                              "klirrfaktor"),
        "gegenkopplung": ("verstaerkung_gegenkopplung", "rueckkopplungsfaktor", "eingangswiderstand_gegenkopplung",
                          "ausgangswiderstand_gegenkopplung", "bandbreite_gegenkopplung"),
        "gleichspannungsverstaerker": ("spannungsverstaerkung", "leistungsverstaerkung", "widerstand_ohm",
                                       "opv_differenz"),
        "hf-verstaerker": ("spannungsverstaerkung", "leistungsverstaerkung", "rauschzahl", "rueckflussdaempfung_db"),
        "selektiver-verstaerker": ("resonanzfrequenz", "bandbreite", "guete_aus_bandbreite", "z_reihe_rlc"),
        "anzapfung-an-schwingkreisen": ("anzapfung_uebersetzung", "anzapfung_widerstand", "resonanzfrequenz"),
    },
    "Wechselstromkreis mit idealen Widerstaenden": {
        "ohmscher-widerstand-im-wechselstromkreis-wirkwiderstand": ("impedanz_ui", "betrag_impedanz",
                                                                    "phasenwinkel_impedanz", "wirkleistung"),
        "induktivitaet-im-wechselstromkreis-ideale-spule": ("blindwiderstand_l", "z_spule", "energie_spule"),
        "kapazitaet-im-wechselstromkreis-idealer-kondensator": ("blindwiderstand_c", "z_kondensator",
                                                                "strom_kondensator"),
        "schaltungen-von-idealen-induktivitaeten-und-idealen-kapazitaeten": ("blindwiderstand_l", "blindwiderstand_c",
                                                                             "energie_spule", "energie_kondensator",
                                                                             "resonanzfrequenz"),
    },
    "Reihenschaltungen bei gemischter Belastung": {
        "wirkwiderstand-und-induktiver-blindwiderstand-in-reihe": ("betrag_impedanz", "blindwiderstand_l",
                                                                   "spannung_gesamt_reihe", "phasenwinkel_impedanz"),
        "verlustwinkel-und-guetefaktor-einer-spule": ("verlustfaktor_spule", "guete_spule", "guete_aus_verlustfaktor"),
        "reihenschaltung-realer-spulen": ("induktivitaet_reihe", "widerstand_reihe", "betrag_impedanz",
                                          "phasenwinkel_impedanz"),
        "wirkwiderstand-und-kapazitiver-blindwiderstand-in-reihe": ("blindwiderstand_c", "betrag_impedanz",
                                                                    "phasenwinkel_impedanz",
                                                                    "teilspannung_wechselstrom"),
        "wirkwiderstand-induktiver-blindwiderstand-und-kapazitiver-blindwiderstand-in-reihe": ("z_reihe_rlc",
                                                                                               "betrag_impedanz"),
    },
    "Parallelschaltungen bei gemischter Belastung": {
        "wirkwiderstand-und-induktiver-blindwiderstand-parallel": ("z_parallel_betrag", "phasenwinkel_parallel",
                                                                   "strom_gesamt_parallel", "wirkleistung"),
        "parallelschaltung-mehrerer-spulen": ("induktivitaet_parallel", "strom_gesamt_parallel"),
        "wirkwiderstand-und-kapazitiver-blindwiderstand-parallel": ("z_parallel_betrag", "phasenwinkel_parallel",
                                                                    "strom_gesamt_parallel"),
        "verlustwinkel-und-guetefaktor-eines-kondensators": ("verlustfaktor_kondensator_parallel",
                                                             "verlustfaktor_kondensator_reihe",
                                                             "guete_aus_verlustfaktor"),
        "wirkwiderstand-induktiver-blindwiderstand-und-kapazitiver-blindwiderstand-parallel": ("z_parallel_rlc",),
    },
    # ------------------------------------------------------------------ Digitaltechnik
    "Logische Schaltungen": {
        "logische-gatter": ("UND", "ODER", "NICHT", "NAND", "NOR", "XOR", "XNOR"),
        "vereinfachung-von-booleschen-ausdruecken": ("aequivalent", "dnf", "knf"),
        "vereinfachung-logischer-schaltnetze": ("aequivalent", "dnf", "knf"),
        "vereinfachung-mit-hilfe-der-schaltalgebra": ("aequivalent",),
        "vereinfachung-mit-hilfe-von-kv-tafeln": ("minterme", "maxterme", "dnf", "knf", "wahrheitstabelle"),
    },
    "Zahlensysteme und Umwandlung von Zahlen": {
        "umwandlung-von-dezimalzahl-in-dualzahl": ("dezimal_zu_dual", "dezimal_zu_basis"),
        "umwandlung-von-dualzahl-in-dezimalzahl": ("dual_zu_dezimal", "basis_zu_dezimal"),
        "umwandlung-von-dezimalzahl-in-hexadezimalzahl": ("dezimal_zu_hex",),
        "umwandlung-von-hexadezimalzahl-in-dezimalzahl": ("hex_zu_dezimal",),
        "umwandlung-von-hexadezimalzahl-in-dualzahl": ("hex_zu_dual",),
        "umwandlung-von-dualzahl-in-hexadezimalzahl": ("dual_zu_hex",),
        "addierer-schaltungen-halbaddierer-und-volladdierer": ("halbaddierer", "volladdierer"),
    },
    "Rechnen": {
        "rechnen-mit-dualzahlen": ("dual_addieren", "dual_subtrahieren", "dual_multiplizieren", "dual_dividieren"),
        "addition-von-dualzahlen": ("dual_addieren", "volladdierer"),
        "subtraktion-von-dualzahlen": ("dual_subtrahieren", "zweierkomplement"),
        "multiplikation-von-dualzahlen": ("dual_multiplizieren",),
        "division-von-dualzahlen": ("dual_dividieren",),
        "rechnen-mit-dem-zweierkomplement-subtraktion-durch-komplementaddition": ("zweierkomplement",
                                                                                   "zweierkomplement_wert",
                                                                                   "dual_subtrahieren"),
    },
    "Schaltalgebra": {
        "rechenregeln-fuer-eine-variable-und-umkehrterme": ("aequivalent", "nte_wurzel", "logarithmus"),
        "kommutativgesetze-der-schaltalgebra": ("aequivalent",),
        "assoziativgesetze-der-schaltalgebra": ("aequivalent",),
        "distributivgesetze-der-schaltalgebra": ("aequivalent",),
        "umkehrgesetze-fuer-eine-variable": ("umstellen", "nte_wurzel", "logarithmus"),
        "umkehrgesetze-fuer-mehrere-variablen": ("umstellen", "nte_wurzel", "logarithmus"),
    },
    "Datenuebertragung": {
        "elementvorrat-und-redundanz": ("entscheidungsgehalt", "redundanz_relativ", "verfuegbarkeit",
                                        "zuverlaessigkeit"),
        "geschwindigkeiten-in-der-datenuebertragung": ("datenrate", "uebertragungsdauer", "bandbreite_grenzen",
                                                       "shannon_kapazitaet"),
        "zeitmultiplexuebertragung": ("tdm_zeitschlitz", "tdm_bitrate", "redundanz_relativ"),
        "fehlerhaeufigkeit-in-der-datenuebertragung": ("bitfehlerrate", "p_fehlerfrei", "zuverlaessigkeit"),
        "modemuebertragung": ("nyquist_kapazitaet", "shannon_kapazitaet", "bitfehlerrate", "snr_db", "baudrate",
                              "modulationsindex_fm", "carson_bandbreite"),
        "uebertragung-ueber-lichtwellenleiter": ("brechzahl", "snellius", "numerische_apertur", "daempfung_lwl",
                                                 "dispersion_impulsverbreiterung", "bandbreite_lwl"),
    },
    # ------------------------------------------------------------------ Grundlagen des Rechnens
    "Grundlagen der Mathematik": {
        "rechenregeln": ("umstellen",),
        "klammerregeln": ("aequivalent",),
        "runden-von-kommazahlen": ("runden", "runden_auf_raster"),
        "bruchrechnen": ("bruch", "gemischte_zahl"),
        "dreisatz-anwenden": ("dreisatz", "dreisatz_antiproportional"),
        "prozentrechnen": ("prozentwert", "grundwert", "prozentsatz", "prozentuale_aenderung"),
        "rechnen-mit-potenzen": ("nte_wurzel",),
        "rechnen-mit-zehnerpotenzen": ("si_praefix", "auto_praefix", "formatiere_si"),
        "rechnen-mit-wurzeln": ("nte_wurzel",),
    },
    "Algebra und Umformungen": {
        "umstellen-von-formeln": ("umstellen",),
        "einheiten-und-vielfache-umrechnen-mit-der-einheit-volt": ("si_praefix", "formatiere_si"),
        "einheiten-und-vielfache-umrechnen-mit-der-einheit-ampere": ("si_praefix", "formatiere_si"),
        "einheiten-und-vielfache-umrechnen-mit-der-einheit-ohm": ("si_praefix", "formatiere_si"),
        "exponentialrechnung": ("exponentialfunktion", "halbwertszeit", "zinseszins", "rc_entladespannung"),
        "rechnen-mit-logarithmen": ("logarithmus",),
    },
    "Trigonometrie": {
        "anwendung-von-sinus": ("augenblickswert", "kreisfrequenz", "effektivwert_sinus", "sinussatz_seite"),
        "anwendung-von-kosinus": ("winkelfunktionen", "kosinussatz", "leistungsfaktor"),
        "pythagoras": ("pythagoras_hypotenuse", "pythagoras_kathete", "betrag_impedanz", "scheinleistung_pq"),
        "winkelfunktionen": ("winkelfunktionen",),
    },
    "Analysis und Erweiterte Mathematik": {
        "differentialrechnung": ("ableitung", "ableitung2"),
        "integralrechnung": ("integral", "mittelwert_integral", "flaeche_zwischen"),
        "rechnen-mit-vektoren": ("vektor_betrag", "einheitsvektor", "skalarprodukt", "kreuzprodukt",
                                 "winkel_vektoren", "kraefte_addieren"),
    },
}

# Seiten, deren EK-Inhalt fehlerhaft, themenfremd oder als reine Rechenregel nicht 1:1 abbildbar ist.
HINWEISE: Dict[str, str] = {
    # --- fehlerhafte / themenfremde EK-Inhalte (hier physikalisch korrekt umgesetzt) ---
    "feldplatte": "EK listet Kondensatorformeln (C = eps A/d ...). Eine Feldplatte ist ein magnetfeldabhaengiger "
                  "Widerstand -> feldplatte_widerstand (Gauss-Effekt).",
    "vielperiodensteuerung": "EK listet Finanzmathematik (NPV, IRR, ROI). Umgesetzt ist die Vielperioden- "
                             "(Schwingungspaket-)Steuerung: P = P_max n/N.",
    "reihenstabilisierung": "EK listet Z-Transformation/DFT. Umgesetzt: Laengstransistor an Z-Diode U_a = U_Z - U_BE.",
    "glaettung-und-siebung": "EK listet Signalglaettung (gleitender Mittelwert, Fourier). Umgesetzt: "
                             "Brummspannung und Siebfaktoren.",
    "daempfung": "EK listet nur mechanische Daempfung; abgedeckt (Feder-Masse) plus elektrische RLC-Daempfung.",
    "berechnung-von-blindleistung-im-wechselstromkreis": "EK: Q_L = U^2 omega L und Q_C = U^2/(omega C) sind "
                                                         "vertauscht. Korrekt: Q_L = U^2/(omega L), Q_C = U^2 omega C.",
    "sternschaltung-mit-unsymmetrischer-ungleichartiger-last": "EK: I_N = sqrt(I_R^2 + I_S^2 + I_T^2) ist falsch "
                                                               "(120-Grad-Versatz). Korrekt: komplexe Zeigersumme.",
    "dreieckschaltung-mit-symmetrischer-last": "EK: I_L = I_Str / sqrt(3) ist vertauscht. Korrekt: I_L = sqrt(3) I_Str.",
    "dreieckschaltung-mit-unsymmetrischer-und-gleichartiger-last": "EK: I_L = I_Ph / sqrt(3) ist vertauscht.",
    "wirkwiderstand-und-induktiver-blindwiderstand-parallel": "EK: cos(phi) = R/sqrt(R^2+X^2) gilt fuer Reihe. "
                                                              "Parallel: cos(phi) = X/sqrt(R^2+X^2).",
    "zuenden-von-thyristoren": "EK-Effektivwertformel sqrt((1+cos a)/2) ist falsch; korrekt "
                               "phasenanschnitt_effektivwert bzw. Mittelwerte gesteuert_m1/gesteuert_b2.",
    "zuenden-von-triacs": "EK-Formel sqrt(2/pi (a - sin a cos a)) ist nicht normiert; korrekt "
                          "phasenanschnitt_effektivwert.",
    "schwingungspaketsteuerung": "EK: U_eff = U_max sqrt(n/N) - korrekt mit dem Effektivwert der Netzspannung.",
    "astabile-kippstufe": "EK-Formeln 0,693 (R1+R2) C sind die NE555-Formeln (-> ne555_astabil); "
                          "Transistor-Multivibrator: multivibrator_periode.",
    "astabile-kippstufe-mit-transistoren": "EK verwendet NE555-Formeln; korrekt T = ln2 (R_B1 C1 + R_B2 C2).",
    "emitterschaltung-mit-stromgegenkopplung": "EK: Vu = -R_C/(R_E + (1+B) r_e) - mit r_e = U_T/I_E korrekt "
                                               "Vu = -R_C/(R_E + r_e).",
    "emitterschaltung-mit-spannungsgegenkopplung": "Wie Stromgegenkopplung; Spannungsgegenkopplung allgemein ueber "
                                                   "verstaerkung_gegenkopplung.",
    "cr-hochpass": "EK: phi = atan(omega RC) - korrekt phi = atan(1/(omega RC)).",
    "bandsperre": "EK: H = 1/(1 + jQ(f/f0 - f0/f)) ist ein Bandpass -> bandpass_2; Bandsperre: bandsperre_2.",
    "schiefe-ebene": "EK: Beschleunigung durch m geteilt ist falsch; a = g (sin a - mu cos a).",
    "schaltnetzgeraet": "EK: L = U_e (1-D) T / dI passt zu keinem Wandler eindeutig; Buck/Boost getrennt umgesetzt.",
    "gleichrichterschaltungen": "EK: U_gl = Uhat - U_r; Mittelwert der Saegezahnwelligkeit ist Uhat - U_ss/2.",
    "fotoelement-und-solarzelle": "EK: I_ph = q G A eta ist dimensionsfalsch; korrekt I_ph = S E A bzw. "
                                  "fotostrom_quanten.",
    "basisschaltung": "EK: Vu = R_C/R_E; mit Emitter als Eingang korrekt Vu = R_C/r_e.",
    "schmitt-trigger-mit-transistoren": "EK-Formeln (+-U_BE) sind nur grobe Naeherungen; allgemein ueber "
                                        "Schwellwerte (schaltschwellen).",
    "kaltleiter-ptc": "EK nutzt nur den linearen Ansatz (Metall-PTC); zusaetzlich exponentieller Keramik-PTC.",
    "spannungsabhaengiger-widerstand-vdr": "EK: R = R0 (U/U0)^n entspricht vdr_widerstand mit n = 1 - alpha.",
    # --- reine Rechenregeln / Identitaeten (keine eigene Rechenformel noetig) ---
    "kirchhoffsche-gesetze": "Knoten-/Maschenregel sind Bilanzgleichungen; Netzwerkberechnung ueber "
                             "knotenpotentiale.",
    "rechenregeln": "Grundrechenarten = Python-Operatoren; umstellen loest Formeln nach jeder Groesse auf.",
    "klammerregeln": "Binomische Formeln = Identitaeten (Tests pruefen sie numerisch).",
    "rechnen-mit-potenzen": "Potenzgesetze = Python ** ; nte_wurzel fuer gebrochene Exponenten.",
    "rechnen-mit-wurzeln": "Wurzelgesetze = Python ** ; nte_wurzel.",
    "rechenregeln-fuer-eine-variable-und-umkehrterme": "Rechengesetze (Kommutativ-, Potenz-, Log-Gesetze) sind "
                                                       "Identitaeten; Schaltalgebra-Gesetze per aequivalent pruefbar.",
    "kommutativgesetze-der-schaltalgebra": "Gesetz - mit aequivalent fuer alle Belegungen nachpruefbar (Tests).",
    "assoziativgesetze-der-schaltalgebra": "Gesetz - mit aequivalent nachpruefbar (Tests).",
    "distributivgesetze-der-schaltalgebra": "Gesetz - mit aequivalent nachpruefbar (Tests).",
    "vereinfachung-mit-hilfe-der-schaltalgebra": "Vereinfachung ist Handarbeit; aequivalent prueft das Ergebnis.",
    "differentialrechnung": "Ableitungsregeln sind symbolisch; numerisch: ableitung/ableitung2.",
    "integralrechnung": "Integrationsregeln sind symbolisch; numerisch: integral (Simpson).",
    "einheiten-und-vielfache-umrechnen-mit-der-einheit-volt": "SI-Praefixe gelten fuer jede Einheit (si_praefix).",
    "einheiten-und-vielfache-umrechnen-mit-der-einheit-ampere": "SI-Praefixe gelten fuer jede Einheit (si_praefix).",
    "einheiten-und-vielfache-umrechnen-mit-der-einheit-ohm": "SI-Praefixe gelten fuer jede Einheit (si_praefix).",
    "elektromagnetismus": "Integralform (Durchflutungsgesetz, Biot-Savart) nur fuer Standardgeometrien "
                          "(gerader Leiter, Spule) als Rechenformel.",
}


def alle_slugs() -> Tuple[str, ...]:
    """Alle EK-Themenseiten (Slug, ohne Doppelte - einige Seiten stehen auf EK in zwei Gruppen)."""
    return tuple(dict.fromkeys(s for gruppe in ABDECKUNG.values() for s in gruppe))


def fehlende_funktionen() -> Dict[str, Tuple[str, ...]]:
    """Slug -> Funktionsnamen, die in et_formeln nicht existieren (soll leer sein)."""
    fehlt = {}
    for gruppe in ABDECKUNG.values():
        for slug, namen in gruppe.items():
            f = tuple(n for n in namen if not callable(getattr(ef, n, None)))
            if f:
                fehlt[slug] = f
    return fehlt


def bericht() -> None:
    funktionen = {n for g in ABDECKUNG.values() for ns in g.values() for n in ns}
    for gruppe, seiten in ABDECKUNG.items():
        print(f"\n=== {gruppe} ===")
        for slug, namen in seiten.items():
            marke = "!" if slug in HINWEISE else " "
            print(f" {marke} {slug:70s} {', '.join(namen)}")
    print(f"\n{len(alle_slugs())} EK-Seiten, {len(funktionen)} verschiedene Funktionen zugeordnet, "
          f"{len(HINWEISE)} Seiten mit Hinweis (!).")
    fehlt = fehlende_funktionen()
    print("Fehlende Funktionen:", fehlt if fehlt else "keine")


if __name__ == "__main__":
    bericht()
